<?php

require_once 'SecureToken.php';

/**
 * Test class for SecureToken.
 * Generated by PHPUnit on 2013-09-29 at 22:58:06.
 */
class SecureTokenTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SecureToken
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SecureToken;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SecureToken::generateToken
     * @todo Add non-trivial test using mocks or something to test time element.
     */
    public function testGenerateToken() {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        
        $url = 'http://www.example.com/example/dir';
        
        // Breaks due to use_helper()
        $this->assertFalse(SecureToken::generateToken($url));
    }

    /**
     * @covers SecureToken::validateToken
     * @todo Add non-trivial test using mocks or something to test time element.
     */
    public function testValidateToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
