<?php

require_once 'UserRole.php';

/**
 * Test class for UserRole.
 * Generated by PHPUnit on 2013-09-29 at 18:37:12.
 */
class UserRoleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserRole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserRole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserRole::setRolesFor
     * @todo Implement testSetRolesFor().
     */
    public function testSetRolesFor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
