<?php

/**
 * Test class for Cron.
 * Generated by PHPUnit on 2010-10-17 at 02:53:52.
 */
class CronTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Cron
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Cron;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }


    /**
     * @todo Implement testGetLastRunTime().
     */
    public function testGetLastRunTime() {
        $this->assertNull($this->object->getLastRunTime());
        $this->assertTrue($this->object->beforeUpdate());
        $this->assertNotNull($this->object->getLastRunTime());
        $this->assertType('int', $this->object->getLastRunTime());
    }


    /**
     * @todo Implement testBeforeUpdate().
     */
    public function testBeforeUpdate() {
        $this->assertNull($this->object->getLastRunTime());
        $this->assertTrue($this->object->beforeUpdate());
        $this->assertNotNull($this->object->getLastRunTime());
    }


    /**
     * @todo Implement testGenerateWebBug().
     */
    public function testGenerateWebBug() {
        $expected = '<!-- About the image below: the website owner chose to have Wolf CMS start a (cron) job on the server by displaying the following image. -->'."\n";
        $expected .= '<img id="wolf-cron-webbug" style="display: none;" src="'.URL_PUBLIC.'/wolf/app/cron.php" width="1" height="1" border="0" />'."\n";

        $actual = $this->object->generateWebBug();

        $this->assertEquals($expected, $actual);
    }

}

?>
