<?php

/**
 * Test class for Plugin.
 * Generated by PHPUnit on 2009-08-18 at 00:34:44.
 */
class PluginTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Plugin
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Plugin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * 
     */
    public function testSetInfos() {
        $info = array(
            'id'          => 'skeleton',
            'title'       => 'Skeleton',
            'description' => 'Provides a basic plugin implementation. (try enabling it!)',
            'version'     => '1.1.0',
            'license'     => 'GPL',
            'author'      => 'Martijn van der Kleijn',
            'website'     => 'http://www.wolfcms.org/',
            'update_url'  => 'http://www.wolfcms.org/plugin-versions.xml',
            'require_wolf_version' => '0.5.5'
        );

        define('CMS_BACKEND', true);
        Plugin::setInfos($info);

        $this->assertArrayHasKey($info['id'], Plugin::$plugins_infos);

        $this->assertEquals($info['id'], Plugin::$plugins_infos[$info['id']]->id);
        $this->assertEquals($info['title'], Plugin::$plugins_infos[$info['id']]->title);
        $this->assertEquals($info['description'], Plugin::$plugins_infos[$info['id']]->description);
        $this->assertEquals($info['version'], Plugin::$plugins_infos[$info['id']]->version);
    }

    /**
     * @todo Implement testActivate().
     */
    public function testActivate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeactivate().
     */
    public function testDeactivate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindAll().
     */
    public function testFindAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCheckLatest().
     */
    public function testCheckLatest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddController().
     */
    public function testAddController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddJavascript().
     */
    public function testAddJavascript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHasSettingsPage().
     */
    public function testHasSettingsPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHasDocumentationPage().
     */
    public function testHasDocumentationPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIsEnabled().
     */
    public function testIsEnabled() {
        $stub = $this->getMock('Plugin');
        $stub->expects($this->any())
        ->method('isEnabled')
        ->will($this->returnValue('foo'));

        $test = $stub->isEnabled('test');

        echo 'TEST-'.$test;

        // Remove the following lines when you implement this test.
        /*
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
         * 
         */
    }

    /**
     * @todo Implement testDeleteAllSettings().
     */
    public function testDeleteAllSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetAllSettings().
     */
    public function testSetAllSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetSetting().
     */
    public function testSetSetting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetAllSettings().
     */
    public function testGetAllSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetSetting().
     */
    public function testGetSetting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
