<?php

/**
 * Test class for Tag.
 * Generated by PHPUnit on 2010-10-17 at 02:33:37.
 */
class TagTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Tag
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tag;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testObjectCreation() {
        $expected = new Tag();
        $expected->id = 1;
        $expected->name = 'an object';

        $actual = new Tag(array(1, 'an object'));
        $this->assertNotEquals($expected, $actual);

        $actual = new Tag(array('id' => 1, 'name' => 'an object'));
        $this->assertEquals($expected, $actual);
    }

}

?>
