<?php

/**
 * Test class for View.
 * Generated by PHPUnit on 2010-10-17 at 00:02:21.
 */
class ViewTest extends PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new View;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    function testFilterKses() {

        use_helper('Kses');
        $string = "<img src='/image' alt='not allowed attr'> <b>!</b><a href=''>not allowed tag</a>";
        $allowed = array(
            'img' => array(
                'src' => array()
            ),
            'b' => array(),
            'br' => array(),
        );

        $expect_string = '<img src=\'/image\'> <b>!</b>not allowed tag';

        $this->assertEquals( $expect_string, kses($string, $allowed));
    }

    function testDecodeEntitiesKses() {

        use_helper('Kses');
        $string = "&#77;f";
        $expect_string = 'Mf';
        $this->assertEquals( $expect_string, kses_decode_entities($string));
    }


    /**
     * @todo Implement testAssign().
     */
    public function testAssign() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
