<?php

require_once dirname(__FILE__).'/../../src/wolf/Framework.php';

/**
 * Test class for AutoLoader.
 * Generated by PHPUnit on 2010-10-17 at 00:02:22.
 */
class AutoLoaderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AutoLoader
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AutoLoader;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * @todo Implement testAddFile().
     */
    public function testAddFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testAddFolder().
     */
    public function testAddFolder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
