<?php

/**
 * Test class for Flash.
 * Generated by PHPUnit on 2010-10-17 at 00:02:21.
 */
class FlashTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Flash
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Flash;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * @todo Implement testGet().
     */
    public function testGet() {
        $actual = Flash::get('TestVar');
        $this->assertNull($actual);

        $expected = 'TestValue';
        Flash::setNow('TestVar', $expected);
        $actual = Flash::get('TestVar');
        $this->assertNotNull($actual);
        $this->assertType('string', $actual);
        $this->assertEquals($expected, $actual);
    }


    /**
     * @todo Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testSetNow().
     */
    public function testSetNow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testClear().
     */
    public function testClear() {
        $expected = 'TestValue';
        Flash::setNow('TestVar', $expected);
        $actual = Flash::get('TestVar');
        $this->assertNotNull($actual);
        $this->assertType('string', $actual);
        $this->assertEquals($expected, $actual);

        Flash::clear();
        $actual = Flash::get('TestVar');
        $this->assertNotNull($actual);
        $this->assertType('string', $actual);
        $this->assertEquals($expected, $actual);
    }


    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
