<?php

require_once dirname(__FILE__).'/../../src/wolf/Framework.php';

/**
 * Test class for Observer.
 * Generated by PHPUnit on 2010-10-17 at 00:02:21.
 */
class ObserverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Observer
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Observer;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * @todo Implement testObserve().
     */
    public function testObserve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testStopObserving().
     */
    public function testStopObserving() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testClearObservers().
     */
    public function testClearObservers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testGetObserverList().
     */
    public function testGetObserverList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testNotify().
     */
    public function testNotify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
